import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');if(t==='light')document.documentElement.classList.add('light');}catch(e){}})()`,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col antialiased">
        <div className="relative min-h-screen">
          <div
            aria-hidden="true"
            className="fixed inset-0 -z-10 pointer-events-none"
            style={{
              background: [
                "radial-gradient(ellipse 70% 55% at 80% 2%, color-mix(in srgb, var(--accent) 10%, transparent), transparent 65%)",
                "radial-gradient(ellipse 60% 65% at 8% 92%, color-mix(in srgb, var(--lime-cs) 8%, transparent), transparent 65%)",
              ].join(", "),
            }}
          />
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
